# Generated by Django 5.1.3 on 2024-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('direccion2', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(choices=[('Tarjeta de credito', 'Tarjeta de credito'), ('Tarjeta de debito', 'Tarjeta de debito')], max_length=100)),
                ('nombre_en_tarjeta', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('expiracion', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('libros', models.ManyToManyField(related_name='carritos', to='catalogo.libro')),
            ],
        ),
    ]
